[tool.ruff]
line-length = 100
target-version = "py311"
extend-select = ["I"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"


