name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity.'
          close-issue-message: 'Closing this issue due to inactivity.'
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity.'
          close-pr-message: 'Closing this PR due to inactivity.'
          exempt-issue-labels: 'pinned,security,backlog'
          exempt-pr-labels: 'pinned,security,backlog'

